name: 'Github Action for git-crypt'

author: 'edpichler'

description: 'Action to Unlock (and then lock) files encrypted by git-crypt, also supporting gpg keys with passphrase'

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: /entrypoint.sh
  post-entrypoint: /exit.sh

branding:
  icon: 'unlock'  
  color: 'green'