---
name: Release version in Github
on:
  push:
    tags:
       - "v*"

jobs:
  release-new-version:
  if: github.ref == 'refs/heads/develop' || github.ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # with:
        #   args: |
        #     darwin-amd64.zip
        #     linux-amd64.zip
        #     windows-amd64.zip