---
name: Release version in Github
on:
  push:
    branches:
      # - master
      # - develop
      - release-ci
    tags:
       - "v*"

jobs:
  release-new-version:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # with:
        #   args: |
        #     darwin-amd64.zip
        #     linux-amd64.zip
        #     windows-amd64.zip